### ISSUE TITLE
Villain Worm?

### ISSUE THREAD

**Issue by evanberkowitz** [evanberkowitz/supervillain#112]
The Villain formulation with W>1 can be read as having a horrible sign problem, since the action contains $2\pi i v dn /W$.  But we could think another way:  execute the sum over v and get a constraint that dn≡0 (mod W).  If we start with dn=0 and find an ergodic scheme to update n while maintaining the constraint, we could do small-κ (Villain-formulation) W≠1 simulations.

**Comment by SethBuesing** [comment]
The simplest answers are often the best. I think we've been in the muck too long and we're overthinking it this, seems like the way to go instead

**Comment by evanberkowitz** [comment]
This wouldn't be instead of the worldline worm, it would be for small κ.
