### ISSUE TITLE
Measure autocorrelation time of wordline `supercurrents'

### ISSUE THREAD

**Issue by alcherman** [evanberkowitz/supervillain#57]
For large lattices in the worldline formulation, it seems that `holonomy' updates are accepted very rarely (acceptances rates of 10^{-3} for N ~ 24 and kappa ~ 0.8).  This suggests that the associated autocorrelation time is at least 10^3, and much longer than any other correlation time.  For example the autocorrelation time of the internal energy is about 3 for kappa ~ .8 .  We should measure the largest autocorrelation time, and if it is indeed huge, consider switching algorithms to e.g. a worm algorithm.

**Comment by evanberkowitz** [comment]
This is indeed markedly improved with the worm, which creates torus-wrapping updates at exactly the rate the configurations like!
